Refactor Testing (#162)
* fix(gh-actions): prevent gh actions from caching packages when lockfile changes

* fix(tests): update tests/repin dependencies for testing

* ci(package): add coverage command and force tests to clean first

* chore(mappings): add sanity check for transfer handler

* fix(token-fees): fix incorrect recognition of strategist fees

* refactor(oracle): price token transfers using the value of the share token instead of the underlying

* style(mappings): style fixes

* refactor(tests): refactor tests to use a stubs/mocks in lieu of archive state emulation

* build(coverage): add coverage step to github flow

* docs(tests): add testing readme

* docs(readme): update intro docs

* refactor(tests): update naming

* fix(lint): whoever wrote this linter needs to step away from the keyboard

* fix(linter): remove file

* fix(lint): fix linter again

* fix(linter): remove file again. thanks git

* chore(generated): update generated code for graph-ts 0.26

* chore(tooling): update apiVersion to 0.0.6

* fix(token-fees): remove querying derived field

* chore(package.json): style refactor

* fix(token-fee): disable strategist fee test until strategy.strategist implemented

* feat: add additional fields to the vault

* fix(oracle): set fantom curve oracle address

* build(graft): add grafting

* fix(oracle): address vault share token pricing issues

* chore(oracle): change oracle load order

* chore(changelog): update changelog

* fix(fantom): make withdraw mapping handler optional

* fix(tests): update pre-commit

* fix(fantom): fix 34m sync halt

* fix(fantom): disable deposit handlers for fantom

* fix(subgraph): removed balanceTokensInvested field

* chore(generated): update generated files

* chore(mappings): clean up unused entitiy fields & update changelog

* feat(mappings): fix fields that weren't being updated correctly

* chore(generated): update generated files

* ci(husky): update husky pre-commit

* chore(fantom): add deposit/withdraw overloads to problematic call handlers

Co-authored-by: 0xkofee <koffee888@protonmail.com>
Co-authored-by: Alex <alex.plutta@googlemail.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,24 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+set +e
+yarn lint:check
+
+# just trying to make sure codegen can run successfully
+yarn codegen
+
+# clean up generated code so it doesnt mess up commits later
 yarn lint:fix
+
+# make sure all changes in generated code have been staged
+git diff --exit-code --quiet generated/
+if [ "$?" -eq 1 ]; then
+	git --no-pager diff --compact-summary generated/
+	echo "^^ There are unstaged changes in the generated code directory. Please stage them for commit."
+	exit 1
+fi
+
+# run tests
+yarn prepare:mainnet
+yarn test
+exit 0
